lib_treasureV1 := treasureV1
lib_treasureV2 := treasureV2/src
lib_middleManA := middleManA/src
lib_middleManB := middleManB/src
app_client := client
tests := tests

$(lib_treasureV1):
	$(MAKE) --directory=$(@)
