#!/usr/bin/env bash

function cleanUp() {
    rm -f *.o
}

# target "all" is a shortcut to all the object file targets.
# each object file target is generated by a static pattern
# rule (GNUmake-only feature) for target "all"
function targetRule_expectObjectFilesBuilt() {
    make -s -f targetRule.mk clean
    make -s -f targetRule.mk
    if ! ( ls *.o )
    then
        echo "fail to produce object files"
        cleanUp
        exit 1
    fi
}

# same as above except that the rule is applied to all 
# targets 
function globalRule_expectObjectFilesBuilt() {
    cleanUp
    make -s -f globalRule.mk
    if ! ( ls *.o )
    then
        echo "fail to produce object files"
        cleanUp
        exit 1
    fi
}

targetRule_expectObjectFilesBuilt
globalRule_expectObjectFilesBuilt

cleanUp

